### ISSUE TITLE
Example code does not run

### ISSUE THREAD

**Issue by tytell** [tsipkens/atems#45]
https://github.com/tsipkens/atems/blob/0e24b57c82b327cd8218f7a3daa0855ae0e298d6/README.md?plain=1#L118

This example won't run as written, because the `opts` variable isn't yet defined.

If a user just copies the text and pastes into Matlab, it won't work.

**Comment by tsipkens** [comment]
This is correct. The text also did not match main_b.m as it was supposed to. This line has been updated accordingly in the README.
