### ISSUE TITLE
Fails with a Matlab error

### ISSUE THREAD

**Issue by tytell** [tsipkens/atems#48]
https://github.com/tsipkens/atems/blob/cd661f02c5b7a3c95215f084e4064a0f7acd4203/%2Btools/write_json.m#L3

When I run `tools.write_json(Aggs, 'test.json');`. Fails with

> Error using jsonencode
> Unable to encode objects of class logical as JSON-formatted text.
> Error in tools.write_json (line 9)
> t0 = jsonencode(var); % generate json text using built-in function 

I think this is a Matlab version incompatibility. Here is my Matlab version info:

> MATLAB Version: 9.14.0.2254940 (R2023a) Update 2
> Operating System: macOS  Version: 12.6.9 Build: 21G726 
> Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by tsipkens** [comment]
This issue could not be replicated, as jsonencode seems to be able to handle logicals on the Windows. A note has been added to the caption to note this limitation instead.

**Comment by tsipkens** [comment]
Issue has now been replicated. Working on a fix.
