### ISSUE TITLE
Matlab crashes

### ISSUE THREAD

**Issue by tytell** [tsipkens/atems#50]
Several of the `main_*` functions will occasionally lock up Matlab on my computer. `main_kmeans` and the final section of `main_0` after `agg.analyze_binary`. I can step through each function line-by-line, so it's not clear where the problem is.

Here is my Matlab and operating system information:

> MATLAB Version: 9.14.0.2254940 (R2023a) Update 2
> Operating System: macOS  Version: 12.6.9 Build: 21G726 
> Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by tsipkens** [comment]
This issue could not be replicated and may be related to the use of macOS. It is possible that this issue is related to the use of the EDM functionality with the macOS version of MATLAB, but it was not possible to verify. This limitation has been noted in the README.
