### ISSUE TITLE
Mistake in function name

### ISSUE THREAD

**Issue by tytell** [tsipkens/atems#51]
https://github.com/tsipkens/atems/blob/cd661f02c5b7a3c95215f084e4064a0f7acd4203/README.md?plain=1#L237

These lines refer to `agg.seg_otsu_rb_orig(...)` and `agg.seg_otsu_rb(...)`. There aren't these functions in the agg directory. I think these should be `agg.seg_otsu_orig(...)` and `agg.seg_otsu(...)`.

**Comment by tsipkens** [comment]
Corrected in: https://github.com/tsipkens/atems/commit/76152abcc9028da6dfff567429ca8813a88ee54a.
