### ISSUE TITLE
Mistaken function name

### ISSUE THREAD

**Issue by tytell** [tsipkens/atems#52]
https://github.com/tsipkens/atems/blob/cd661f02c5b7a3c95215f084e4064a0f7acd4203/README.md?plain=1#L295

README refers to `pp.kook*(...)`. I think this should be `pp.hough_kook*`.

**Comment by tsipkens** [comment]
Corrected in: https://github.com/tsipkens/atems/commit/6477b5bc00674841f7da5df9b8212273c8e5d20b.
