### ISSUE TITLE
Onnx file can't be downloaded.

### ISSUE THREAD

**Issue by 1093465452** [tsipkens/atems#54]
Dear tsipkens professor.
  Hello, the link for the file "FPN-resnet50-imagenet.onnx" is invalid, and the file can't be downloaded, could you share the file link again?
![FPN-resnet50-imagenet](https://github.com/user-attachments/assets/0d39fd80-aa6b-45cd-84f7-010876321597)

**Comment by tsipkens** [comment]
The file has been temporarily reuploaded to a different GitHub repository. It can be downloaded here: https://github.com/tsipkens/FPN-resnet50-imagenet.
